bboard_prj/bboard_prj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include(('bboardapp.urls'), namespace='bboardapp')),
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('contact/', include('bboardapp.urls')),
    path('posts/', include('bboardapp.urls')),
    path('sign/', include('sign.urls')),
    path('post_create/', include('bboardapp.urls')),
    # path('post_update/', include('bboardapp.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bboard_prj/bboardapp/urls.py
from django.urls import path

from .views import PostList, PostDetail, PostCreate, СheckComment, PostUpdate, FilterPostsView, FilterMyPostsView, \
    Search, NewsListView, NewsAddView, NewsDetail

app_name = 'bboardapp'
urlpatterns = [
    path('', PostList.as_view(), name='posts'),
    path('filter/', FilterPostsView.as_view(), name='filter'),
    path('my_posts/', FilterMyPostsView.as_view(), name='my_posts'),
    path('search/', Search.as_view(), name='search'),
    path('<int:pk>', PostDetail.as_view(), name='post_detail'),
    path('news/', NewsListView.as_view(), name='news'),
    path('news/<int:pk>', NewsDetail.as_view(), name='news_detail'),
    path('news_add/', NewsAddView.as_view(), name='news_add'),
    path('post_create/', PostCreate.as_view(), name='post_create'),
    path('post_update/<int:pk>', PostUpdate.as_view(), name='post_update'),
    path('comment_update/<int:pk>', СheckComment.as_view(), name='cmnt_updt'),
    # path('run_function/', views.run_function),
    # path('image-request/', image_request, name='image-request'),
]

bboard_prj/sign/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from .views import BaseRegisterView
from .views import upgrade_me

urlpatterns = [
    path('login/', LoginView.as_view(template_name='sign/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='sign/logout.html'), name='logout'),
    path('signup/', BaseRegisterView.as_view(template_name='sign/signup.html'), name='signup'),
    path('upgrade/', upgrade_me, name='upgrade'),
]

bboard_prj/bboardapp/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import User
from datetime import datetime

from ckeditor_uploader.fields import RichTextUploadingField


# категории объявлений
class Category(models.Model):
    category_name = models.CharField(max_length=50, unique=True)  # - название категории.

    def __str__(self):
        return self.category_name


# авторы объявлений
class Author(models.Model):
    author_user = models.OneToOneField(User, on_delete=models.CASCADE)  # - cвязь «один к одному» с встроенной моделью пользователей User

    def __str__(self):
        return self.author_user.username


class UploadImage(models.Model):
    caption = models.CharField(max_length=200)
    image = models.ImageField(upload_to='images')

    def __str__(self):
        return self.caption


class UploadVideo(models.Model):
    caption = models.CharField(max_length=200)
    image = models.FileField(upload_to='video')

    def __str__(self):
        return self.caption


# объявления
class Post(models.Model):
    post_author = models.ForeignKey(Author, verbose_name='Автор', on_delete=models.CASCADE)  # - связь «один ко многим» с моделью Author;
    post_category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE, default=0)  # - связь «один ко многим» с моделью Category;
    post_date = models.DateTimeField('Дата', auto_now_add=datetime.now())                    # - автоматически добавляемая дата и время создания;
    post_title = models.CharField('Заголовок', max_length=124)          # - заголовок;
    post_text = RichTextUploadingField(verbose_name='Полный текст статьи', help_text='Тут нужно ввести всю статью в формате HTML')
    post_image = models.ImageField(upload_to='images')
    post_video = models.CharField('Ссылка на видео', max_length=500)
    # post_video = models.FileField(upload_to='video')

    # - Метод preview(), который возвращает начало поста (предварительный просмотр) длиной 124 символа и добавляет многоточие в конце.
    def preview(self):
        return str(self.post_text)[0:125] + '...'

    # def __str__(self):
    #     return str(self.value)


# комментарии пользователей к объявлению
class Comment(models.Model):
    comment_post = models.ForeignKey(Post, on_delete=models.CASCADE)     # - связь «один ко многим» с моделью Post;
    comment_user = models.ForeignKey(User, on_delete=models.CASCADE)     # - связь «один ко многим» со встроенной моделью User;
    comment_text = models.TextField()                                             # - текст комментария;
    comment_datetime = models.DateTimeField(auto_now_add=datetime.now())  # - дата и время создания комментария;
    comment_accept = models.CharField(max_length=2, default='')  # - =X, если коммент акцептован;
    comment_reject = models.CharField(max_length=2, default='')  # - =X, если коммент удален;

    def __str__(self):
        return f"{self.comment_text} - {self.comment_post}"

    class Meta:
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"


# Коды подтверждения (например: при регистрации пользователя)
class CodeConfirmation(models.Model):
    code_confirmation = models.CharField(max_length=20, default='')
    code_confirmation_datetime = models.DateTimeField(auto_now_add=datetime.now())
    code_confirmation_type = models.IntegerField(default=0)
    code_confirmation_email = models.CharField(max_length=200, default='')

# объявления
class News(models.Model):
    news_author = models.ForeignKey(Author, verbose_name='Автор', on_delete=models.CASCADE)  # - связь «один ко многим» с моделью Author;
    news_date = models.DateTimeField('Дата', auto_now_add=datetime.now())                    # - автоматически добавляемая дата и время создания;
    news_title = models.CharField('Заголовок', max_length=124)          # - заголовок;
    news_text = RichTextUploadingField(verbose_name='Полный текст новости')
    news_image = models.ImageField(upload_to='images')

    # - Метод preview(), который возвращает начало поста (предварительный просмотр) длиной 124 символа и добавляет многоточие в конце.
    def preview(self):
        return str(self.news_text)[0:125] + '...'

bboard_prj/templates/acc_active_email.html
{% autoescape off %} 
Hi {{ user.username }}, 
Please click on the link to confirm your registration, 
http://{{ domain }}{% url 'activate' uidb64=uid token=token %} 
{% endautoescape %} 

bboard_prj/templates/comment_updt.html
{% extends 'flatpages/default.html' %}

{% block title %}
    <head>
        <title>An example</title>
        <a target="_blank"
           class="btn btn-info pull-right"
           href="{% url СheckComment comment_updt.pk %}/?next={{ comment_updt.link_for_item|urlencode:'' }}">
           Check It Out
        </a>
        <script>
            function call_counter(url, pk) {
                window.open(url);
                $.get('СheckComment/'+pk+'/', function (data) {
                    alert("counter updated!");
                });
            }
        </script>
    </head>

{% endblock title %}

{% block content %}
    <b><a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="8" color="LightSkyBlue">Комментарий</font></a></b>
    <hr>
    <font size="5" color="LemonChiffon"><b>Дата:</b> {{ comment_updt.comment_datetime }}</font><br>
    <font size="5" color="LemonChiffon"><b>Текст:</b> {{ comment_updt.comment_text }}</font><br>
<!--    <font size="5" color="LemonChiffon">{{ comment_updt.pk }}</font>-->
    <br>
    <form action="" method="post">
        {% csrf_token %}
        {% if comment_updt.comment_accept == '' %}
            <button type="submit" class="btn btn-success" name="success">Принять</button>
            <button type="submit" class="btn btn-danger" name="reject">Удалить</button>
        {% else %}
            <h1><span style = "color: PaleGreen"> Данный комментарий был принят </span></h1>
        {% endif %}
    </form>
{% endblock content %}

bboard_prj/templates/contact.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block content %}
    Здесь разместим контактную информацию
{% endblock content %}

bboard_prj/templates/main.html
<html>
    <head>
        <title> Simple SignUp/SignIn app</title>
    </head>
    <body>
        <div>
            <h1><a href="/">Simple SignUp/SignIn app</a></h1>
        </div>
        {% block content %}
        {% endblock %}
    </body>
</html>

bboard_prj/templates/news.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block content %}
    <div class="background" id="home" style="background-color: rgb(105, 105, 105);">

    <form action="" method="post">
        {% csrf_token %}

        <a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="7" color="LightSkyBlue"> Наши новости </font></a>
        <!-- Если в переменной next_sale будет None, то выведется указанный в фильтре текст -->
        <h5><span style = "color: LemonChiffon">{{ next_action|default_if_none:"Чуть позже сообщим о новой акции!" }}</span></h5><br>

        {% if news %}
            {% for serv in object_list %}
                <!-- Выводим заголовок-->
                <br>
                <em><font size="6" color="LemonChiffon">Дата публикации: {{ serv.news_date|date:"d.m.Y" }}</font></em><br>
                <h3><font size="5" color="LemonChiffon">{{ serv.news_title }}</font></h3><br>
                <!-- Выводим автора и дату публикации -->
                <!-- Выводим текст -->
                <font size="4" color="LemonChiffon">{{ serv.news_text|safe }}</font><br><br>
            {% endfor %}
        {% else %}
            <h2>Объявлений нет!</h2>
        {% endif %}
    </form>
{% endblock content %}

bboard_prj/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <b><a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="8" color="LightSkyBlue"> Создание новости </font></a></b>
    <hr>
<!--    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem; background-image: url(&quot;../media/images/s2.jpg&quot;);">-->
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <font size="5" color="LemonChiffon">Дата: {{ form.news_date|date:"d-m-Y H:i" }}</font>
        <br><br>
        {% if user.is_authenticated %}
            <font size="5" color="LemonChiffon">Автор: {{ user.username }}</font>
        {% else %}
            Not logged in.
        {% endif %}
<!--        Автор: {{ form.post_author }}-->
        <br><br>
        <font size="5" color="LemonChiffon">Заголовок:  {{ form.news_title }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Текст:  {{ form.news_text }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Категория:  {{ form.news_category }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Картинка: {{ form.news_image }}</font>
        <br><br>
        <button type="submit" class="btn btn-success">Загрузить</button><br>
    </form>
{% endblock content %}

bboard_prj/templates/news_detail.html
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Post -->
{% block title %}
News
{% endblock title %}

<!-- В контенте на странице мы выводим сам пост, идентификатор которого был передан в url -->
{% block content %}
    <b><a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="8" color="LightSkyBlue"> Новость </font></a></b><br>
    <b><font size="5" color="LemonChiffon">{{ news_detail.news_title }}</font></b><br>
    <font size="5" color="LemonChiffon">Автор: {{ news_detail.news_author.author_user }}</font><br>
    <font size="5" color="LemonChiffon">Дата: {{ news_detail.news_date|date:"d M Y" }}</font><br>
    <font size="5" color="LemonChiffon">{{ news_detail.news_text|safe }}</font>
    <br>
{% endblock content %}

bboard_prj/templates/post_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <b><a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="8" color="LightSkyBlue"> Создание поста </font></a></b>
    <hr>
<!--    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem; background-image: url(&quot;../media/images/s2.jpg&quot;);">-->
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <font size="5" color="LemonChiffon">Дата: {{ form.post_date|date:"d-m-Y H:i" }}</font>
        <br><br>
        {% if user.is_authenticated %}
            <font size="5" color="LemonChiffon">Автор: {{ user.username }}</font>
        {% else %}
            Not logged in.
        {% endif %}
<!--        Автор: {{ form.post_author }}-->
        <br><br>
        <font size="5" color="LemonChiffon">Заголовок:  {{ form.post_title }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Текст:  {{ form.post_text }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Категория:  {{ form.post_category }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Картинка: {{ form.post_image }}</font>
        <br><br>
        <font size="5" color="LemonChiffon">Видео: {{ form.post_video }} *если видео не требуется - ставь пробел в поле</font>
        <br><br>
        <button type="submit" class="btn btn-success">Загрузить</button><br>
    </form>
{% endblock content %}

bboard_prj/templates/post_create_notification.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>{{ text }}</p>
<h3><a href="{{ link }}">{{ text|safe }}</a></h3>
</body>
</html>

bboard_prj/templates/post_detail.html
{% extends 'flatpages/default.html' %}

<!-- Название у нас будет Post -->
{% block title %}
Post
{% endblock title %}

<!-- В контенте на странице мы выводим сам пост, идентификатор которого был передан в url -->
{% block content %}
    <b><a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="8" color="LightSkyBlue"> Объявление </font></a></b>
    <br>
    <b><font size="5" color="LemonChiffon">{{ post_detail.post_title }}</font></b>
    <br>
    <font size="5" color="LemonChiffon">Автор: {{ post_detail.post_author.author_user }}</font>
    <br>
    <font size="5" color="LemonChiffon">Дата: {{ post_detail.post_date|date:"d M Y" }}</font>
    <br>
    <font size="5" color="LemonChiffon">Рейтинг: {{ post_detail.post_rating }}</font>
    <br>
    <font size="5" color="LemonChiffon">{{ post_detail.post_text|safe }}</font>
    <br>

    <div class="contact-single">
        <li style="list-style: none">
            <span><b><font size="5" color="LemonChiffon">Комментарии:</font></b>
                <br>
                {% csrf_token %}
                {% for cmnt in post_detail.comment_set.all %}
                    {% if cmnt.comment_reject != 'X' %}
                    <font size="5" color="LemonChiffon">Дата: {{ cmnt.comment_datetime }}</font>
                    <br>
                    {% if cmnt.comment_accept == 'X' %}
                        <span style="color: PaleGreen">КОММЕНТАРИЙ ПРИНЯТ</span>
                    {% endif %}
                    <font size="5" color="LemonChiffon">Текст:</font>
                    <br>
                    <font size="5" color="LemonChiffon"><a href="../comment_update/{{ cmnt.id }}">{{ cmnt.comment_text }}</a></font>
                    <br>
                    <br>
                    {% endif %}
                {% endfor %}
                <br>
                <br>
            </span>
        </li>

        <h3 class="editContent"><span class="subtittle editContent" style="color: DarkSalmon">Оставить комментарий</span></h3>
        <form action="#" method="post" class="mt-4">
            {% csrf_token %}
            <div class="form-group editContent">
                <label for="comment_text" class="editContent">
                    <font size="5" color="LemonChiffon">Ваш комментарий *</font>
                    <textarea class="form-control border" rows="5" cols="150" name="comment_text" id="comment_text" required="">
                    </textarea>
                </label>
            </div>
            <button type="submit" class="mt-3 btn-success btn-block py-3">
                Отправить
            </button>
        </form>
    </div>
{% endblock content %}

bboard_prj/templates/post_search.html
<!--  наследуемся от шаблона default.html, который мы создавали для flatpages -->
{% extends 'flatpages/default.html' %}

{% load custom_filters %}
{% load custom_tags %}

<!-- Название у нас будет posts -->
{% block title %}
Posts
{% endblock title %}

<!-- В контенте на странице мы выводим все посты -->
{% block content %}
   <h1><span style = "color: blue"> Новости для Вас </span></h1>
   <span style = "color: red"> Всего новостей/статей: {{ news|length }} ------ Текущая дата: {% current_time '%b %d %Y %A' %}</span>
   <!-- Если в переменной next_sale будет None,
   то выведется указанный в фильтре текст -->
   <h5><span style = "color: magenta"> {{ next_action|default_if_none:"Чуть позже сообщим о новой акции!" }} </span></h5>
   <br>

   {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
   <form action="" method="get">
       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}
       {{ filterset.form.as_p }}
       {# Добавим кнопку отправки данных формы #}
       <input type="submit" value="Найти" />
       <br>
       <br>
   </form>

   {% if news %}
      {% for serv in object_list %}
          <!-- Выводим заголовок-->
          <tr><td><h3>{{ serv.post_title|censor }}</h3></td></tr>
          <!-- Выводим автора -->
          <!--<td><h4>{{ serv.post_author.author_user }}</h4></td>-->
          <!-- Выводим дату публикации -->
          <tr><td><h5>Дата публикации: {{ serv.post_date|date:"d.m.Y" }}</h5></td></tr>
          <!-- Выводим 20 символов текста статьи -->
          <tr><td>{{ serv.preview|censor|truncatewords:20 }}</td></tr>
          <br><br>
      {% endfor %}
   {% else %}
      <h2>Ничего не найдено!</h2>
   {% endif %}

   {# Добавляем пагинацию на страницу #}
<!--   {% for p in paginator.page_range %}-->
<!--       {% if page_obj.number == p %}-->
<!--            <li class="page-num page-num-selected">{{ p }}</li>-->
<!--            {% elif p >= page_obj.number|add:-2 and p <= page_obj.number|add:2  %}-->
<!--            <li class="page-num">-->
<!--            <a href="?page={{ p }}">{{ p }}</a></li>-->
<!--       {% endif %}-->
<!--   {% endfor %}-->

   {# Информация о предыдущих страницах #}
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
<!--           ...-->
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {# Информация о текущей странице #}
   {{ page_obj.number }}

   {# Информация о следующих страницах #}
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}
{% endblock content %}

bboard_prj/templates/post_update.html
{% extends 'flatpages/default.html' %}

{% block content %}
    <b><a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="8" color="LightSkyBlue"> Редактирование поста </font></a></b>
    <hr>
<!--    <section class="ab-info-main py-md-5 py-4 editContent" style="padding-left: 3rem; padding-right: 3rem; background-image: url(&quot;../media/images/s2.jpg&quot;);">-->
    <form action="" method="post" enctype="multipart/form-data">
<!--        <font size="4" color="LemonChiffon">user.pk: {{ user.pk }}</font><br><br>-->
<!--        <font size="4" color="LemonChiffon">form.post_author_id: {{ form.post_author__pk }}</font><br><br>-->

        {% if user.is_authenticated %}
                {% csrf_token %}
                <font size="5" color="LemonChiffon">Дата: {{ form.post_date|date:"d-m-Y H:i" }}</font>
                <br><br>
                <font size="5" color="LemonChiffon">Автор: {{ user.username }}</font>
<!--            Автор: {{ form.post_author }}-->
                <br><br>
                <font size="5" color="LemonChiffon">Заголовок:  {{ form.post_title }}</font>
                <br><br>
                <font size="5" color="LemonChiffon">Текст (введите текст без дополнительных тегов):</font><br>
                <font size="5" color="LemonChiffon">{{ form.post_text }}</font>
                <br><br>
                <font size="5" color="LemonChiffon">Категория:  {{ form.post_category }}</font>
                <br><br>
                <font size="5" color="LemonChiffon">Картинка: {{ form.post_image }}</font>
                <br><br>
                <font size="5" color="LemonChiffon">Видео: {{ form.post_video }} *если видео не требуется - ставь пробел в поле</font>
                <br><br>
                <button type="submit" class="btn btn-success">Принять изменения</button><br>
        {% else %}
            <h5><font size="5" color="LemonChiffon"> Вы не авторизованы </font></h5>
        {% endif %}
    </form>
{% endblock content %}

bboard_prj/templates/posts.html
{% extends 'flatpages/default.html' %}

{% load static %}

{% block title %}
Posts
{% endblock title %}

{% block search %}
    <div class="search-bar w3layouts-newsletter">
        <h3 class="sear-head editContent" style = "color: LemonChiffon">Поиск топика</h3>
        <form action="{% url 'bboardapp:search' %}" method="get" class="d-flex editContent" >
            {% csrf_token %}
            <input type="search" placeholder="Введите название..." name="q" class="form-control" required="">
            <button type="submit" class="btn1 btn" ><span class="fa fa-search" aria-hidden="true"></span></button>
        </form>
    </div>
    <form action="{% url 'bboardapp:filter' %}" method="get">
        <div class="left-side my-4">
            <h3 class="sear-head editContent" style = "color: LemonChiffon">Категории</h3>
            <ul class="w3layouts-box-list">
            {% for categ in view.get_category %}
                <li class="editContent" >
                <input type="checkbox" class="checked" name="category_name" value="{{ categ.category_name }}">
                <span class="span editContent" style = "color: LemonChiffon">{{ categ.category_name }}</span>
                </li>
            {% endfor %}
            </ul>
        </div>
        <button type="submit">Найти</button>
    </form>
    <br><br>
    <form action="{% url 'bboardapp:my_posts' %}" method="get">
        <button type="submit">Мои посты</button>
    </form>
{% endblock search %}

{% block content %}
    <div class="background" id="home" style="background-color: rgb(105, 105, 105);">
<!--        # background-image: url(&quot;../media/images/s2.jpg&quot;);">-->

    <form action="" method="post">
        {% csrf_token %}

        <a style = "font-family: &quot;Source Sans Pro&quot;, sans-serif;"><font size="7" color="LightSkyBlue"> Наши объявления </font></a>
        <!-- Если в переменной next_sale будет None, то выведется указанный в фильтре текст -->
        <h5><span style = "color: LemonChiffon">{{ next_action|default_if_none:"Чуть позже сообщим о новой акции!" }}</span></h5>
        <br>

        {% if posts %}
            {% for serv in object_list %}
                <!-- Выводим заголовок-->
                <br><br>
                <h3><a href="../posts/{{serv.id}}"><font size="7" color="LemonChiffon">{{ serv.post_title }}</font></a></h3>
                <!-- Выводим автора и дату публикации -->
                <em><font color="LemonChiffon">Автор: {{ serv.post_author.author_user }}  ...  Дата публикации: {{ serv.post_date|date:"d.m.Y" }}</font></em>
                <!-- Выводим текст -->
                <font size="4" color="LemonChiffon">{{ serv.post_text|safe }}</font>
                <a href="../post_update/{{serv.id}}"><font size="3" color="white">Редактировать</font></a>
                <br><br>
            {% endfor %}
        {% else %}
            <h2>Объявлений нет!</h2>
        {% endif %}
    </form>
{% endblock content %}